
ht:
	clear
	gcc -Wall -g hash_table.c linked_list.c unit_tests.c -o unit_tests -lcunit
	valgrind ./unit_tests

ll:
		clear
		gcc -Wall -g linked_list.c linked_test.c -o unit_tests -lcunit
		./unit_tests
